[package]
name = "cpu_test"
version = "0.1.0"
authors = ["chase"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.2.0"
itertools = "0.8.1"
time = "0.2.0"
